install.packages("moments")
data(mtcars)
names(mtcars)
library(moments)
skewness(mtcars$carb)
kurtosis(mtcars$carb)
plot(density(mtcars$carb))
summary(mtcars$carb)
table(mtcars$carb , mtcars$mpg)
cov(mtcars$carb , mtcars$mpg)
cor(mtcars$carb , mtcars$mpg)
tapply(mtcars$carb , mtcars$mpg)
summary(mtcars)
plot(mtcars$carb)
install.packages("coronavirus")
library(coronavirus)
names(coronavirus)
plot(coronavirus$population)
pie(table(coronavirus$population))
plot(x = coronavirus$population , 
y = rep(0 , 
nrow(coronavirus)),
ylab = "",yaxt="n")
boxplot(x = coronavirus$population , xlab = "Population" , horizontal = TRUE)
hist(coronavirus$population)
hist(x = coronavirus$population , breaks = 100)
plot(density(coronavirus$population))
points(x = coronavirus$population , y = rep(-0.0005 , nrow(coronavirus)))
plot(density(mtcars$mpg))
points(x = mtcars$mpg , y = rep(-0.0005 , nrow(mtcars)))
spineplot(x = mtcars$mpg , y = mtcars$cyl)
mosaicplot(x = table(mtcars$mpg , mtcars$cyl) , las = 3)
mosaicplot(x = table(coronavirus$population , coronavirus$cases) , las = 3)
plot(x = coronavirus$date , y = coronavirus$cases)
plot(x = table(coronavirus$cases) , type = "l")
barplot(tapply(coronavirus$cases , coronavirus$date , mean))

